
## during development ##

#spring.jpa.hibernate.ddl-auto=${user.database.hibernate.ddl}
#spring.jpa.defer-datasource-initialization= true
#spring.sql.init.mode=always
#spring.datasource.driver-class-name=${user.database.driver}
#
### database information ##
#spring.jpa.properties.hibernate.dialect =${user.database.platform.dialect}
#
#
### User details ##
#spring.datasource.url=${user.database.url}
#spring.datasource.username=${user.database.username}
#spring.datasource.password=${user.database.password}

logging:
  level:
    org:
      hibernate:
        stat: debug

spring:
  cloud:
    gcp:
      security:
        firebase:
          enabled: false


  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/alumni-network-1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:

    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://securetoken.google.com/alumni-network-experis-54ed8"
          jwk-set-uri: "https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com"